In [18]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import ast

In [19]:
labelling_file='labels_my-project-name_2024-03-30-01-29-11.csv'
df=pd.read_csv(labelling_file)
df

,26K5RJ3ZW2IIMR2KJFDXSDSKTHUW4E7NMINPCS2MHC6HAQ23BTJA.jpg,[None]
0,2ADGDWDYAXB4AK47FFOPLEDWXFIY7XMMRADYJAJAJRCCGP...,[Tower Bridge]
1,2AFWOO37IJZG4GOU5GMTBKNJX2OQTRQCOZB6YRD5Z72EJP...,[None]
2,2AUW6KOSKR24Q624P4BAXVOE3DDAZVO75A6UHZUBE4MREG...,[Big Ben]
3,2BD5NPKTUNCUIKKYTNJLYABRHG2AMG4GSQO67SM2FK5CM3...,[Tower Bridge]
4,2CMDM4PL4E6UW2YYX3THTWYO6ZLB73CHNMTWJCTJKOAU76...,[None]
...,...,...
898,ZUGAWZ7VC6DURHHYMIPAEU6WQUKRQNCSKL23RSZTI3NMXG...,[None]
899,ZWFZWTA6UQV6BPHDXUWANP4D2ROCURCU564QN2ADH27KCB...,[Tower Of London]
900,ZWKU32WWE2IPEEWZGGYYCSFLU6PNGZIF52UYE6ROLGE673...,"[Lastminute.com London Eye,Palace Of Westminst..."
901,ZXNYLU5WQHHLKBJ6IZ6XF4VPRXWB4CBU53PSXGSIOX57VG...,"[Lastminute.com London Eye,Big Ben]"
902,ZY2GZEYKSC222CIL3EO2KH3ULHHZWEJSCYPGICTWIPAETU...,[None]

In [20]:
#Rename columns to match the format of the data + Remove file extension from the image_id
df.columns = ['image_id', 'ground_truth']
df['image_id'] = df['image_id'].str.split('.').str[0]
df

,image_id,ground_truth
0,2ADGDWDYAXB4AK47FFOPLEDWXFIY7XMMRADYJAJAJRCCGP...,[Tower Bridge]
1,2AFWOO37IJZG4GOU5GMTBKNJX2OQTRQCOZB6YRD5Z72EJP...,[None]
2,2AUW6KOSKR24Q624P4BAXVOE3DDAZVO75A6UHZUBE4MREG...,[Big Ben]
3,2BD5NPKTUNCUIKKYTNJLYABRHG2AMG4GSQO67SM2FK5CM3...,[Tower Bridge]
4,2CMDM4PL4E6UW2YYX3THTWYO6ZLB73CHNMTWJCTJKOAU76...,[None]
...,...,...
898,ZUGAWZ7VC6DURHHYMIPAEU6WQUKRQNCSKL23RSZTI3NMXG...,[None]
899,ZWFZWTA6UQV6BPHDXUWANP4D2ROCURCU564QN2ADH27KCB...,[Tower Of London]
900,ZWKU32WWE2IPEEWZGGYYCSFLU6PNGZIF52UYE6ROLGE673...,"[Lastminute.com London Eye,Palace Of Westminst..."
901,ZXNYLU5WQHHLKBJ6IZ6XF4VPRXWB4CBU53PSXGSIOX57VG...,"[Lastminute.com London Eye,Big Ben]"
902,ZY2GZEYKSC222CIL3EO2KH3ULHHZWEJSCYPGICTWIPAETU...,[None]

In [21]:
data_1='google_vision_sp_detection.csv'
df_1=pd.read_csv(data_1) 

df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271 entries, 0 to 270
Data columns (total 4 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   image_id                        271 non-null    object
 1   google_vision_sp_detection      64 non-null     object
 2   google_vision_sp_score          271 non-null    float64
 3   google_vision_sp_response Time  270 non-null    float64
dtypes: float64(2), object(2)
memory usage: 8.6+ KB

In [22]:
df_1['google_vision_sp_detection'].unique()

array([nan, 'Lastminute.com London Eye', 'Tower Bridge',
       'The British Museum', 'Tower Of London', 'Big Ben',
       'Palace Of Westminster', 'Trafalgar Square', 'Westminster Bridge'],
      dtype=object)

In [39]:
df_1 = df_1.fillna('None')
df_1.image_id[1]
df_1['image_id'] = df_1['image_id'].str.split('.').str[0]

In [24]:
df_1['google_vision_sp_detection'].unique()

array(['None', 'Lastminute.com London Eye', 'Tower Bridge',
       'The British Museum', 'Tower Of London', 'Big Ben',
       'Palace Of Westminster', 'Trafalgar Square', 'Westminster Bridge'],
      dtype=object)

In [25]:
data_2='vision_openai_sp_detection_edited.csv'
df_2=pd.read_csv(data_2) 

df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271 entries, 0 to 270
Data columns (total 3 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   image_id                     271 non-null    object
 1   vision_openai_sp_detection   271 non-null    object
 2   vision_openai_response_time  271 non-null    float64
dtypes: float64(1), object(2)
memory usage: 6.5+ KB

In [26]:
df_2['vision_openai_sp_detection'].unique()

array(['Big Ben', 'None', 'The Shard', 'Tower Bridge', 'Trafalgar Square',
       'Westminster Bridge', 'The British Museum',
       'Lastminute.com London Eye', 'Palace Of Westminster',
       '30 St Mary Axe (the Gherkin)', 'The Palace Of Westminster',
       'Tower Of London'], dtype=object)

In [30]:
# Drop images where "Error in API call" and get % of overall dataset
# For Any row in detectionss_vision_openai, replace '.' at the end of the string with empty space and Capatilize the first letter of every substring
def standardize_format(s):
    if pd.isna(s):
        return 'None'
    if s == 'The Palace Of Westminster':
        return 'Palace Of Westminster'
    # Remove full stops at the end
    ##if s== 'Kensington Palace':
       ## return 'None'
    if s == '30 St Mary Axe (the Gherkin)':
        return '30 St Mary Axe (The Gherkin)'
    s = s.rstrip('.')
    # Capitalize the first letter of each substring
    s = ' '.join(word.capitalize() for word in s.split())
    return s

# Apply the function to the DataFrame column
df_2['vision_openai_sp_detection'] = df_2['vision_openai_sp_detection'].apply(standardize_format)
df_1['google_vision_sp_detection'] = df_1['google_vision_sp_detection'].apply(standardize_format)

In [31]:
df_1['google_vision_sp_detection'].unique()

array(['None', 'Lastminute.com London Eye', 'Tower Bridge',
       'The British Museum', 'Tower Of London', 'Big Ben',
       'Palace Of Westminster', 'Trafalgar Square', 'Westminster Bridge'],
      dtype=object)

merged_df = pd.merge(df_2, df_1, on='image_id', how='inner')
columns_to_drop = merged_df.columns[[2, 18]].tolist()
merged_df = merged_df.drop(columns=columns_to_drop)
merged_df.rename(columns={'description': 'detections_google_vision'}, inplace=True)

merged_df

In [32]:
df_2['vision_openai_sp_detection'].unique()

array(['Big Ben', 'None', 'The Shard', 'Tower Bridge', 'Trafalgar Square',
       'Westminster Bridge', 'The British Museum',
       'Lastminute.com London Eye', 'Palace Of Westminster',
       '30 St Mary Axe (the Gherkin)', 'Tower Of London'], dtype=object)

In [37]:
df_2.image_id[1]

'TKUAUGKMUUXUYKFE53MLJ64UC2LBDZK22CKY2JXF22ELUSIBXEEA'

0

array(['None', 'The Shard', '30 St Mary Axe (The Gherkin)', 'Big Ben',
       'Tower Bridge', 'The British Museum', 'Trafalgar Square',
       'Lastminute.com London Eye', 'Westminster Bridge',
       'Palace Of Westminster', 'Tower Of London', 'Wembley Stadium'],
      dtype=object)

In [40]:
merged_df = pd.merge(df_1, df_2, on='image_id', how= 'inner')
merged_df

,image_id,google_vision_sp_detection,google_vision_sp_score,google_vision_sp_response Time,vision_openai_sp_detection,vision_openai_response_time
0,AQ7Q666WK2OXZKIQBQVWPRC5D2M6XFBEHFKQ3MRFV2T2OM...,None,0.0,0.406496,Big Ben,6.470501
1,TKUAUGKMUUXUYKFE53MLJ64UC2LBDZK22CKY2JXF22ELUS...,None,0.0,0.30369,None,3.266893
2,5FF4Y4LHR5EYDJ7K25U5HUMKWANKYONMVSHQ7ILHOHAX53...,None,0.0,0.341127,The Shard,13.263211
3,OQNB4FXPW3SUEF2CRCJNENGESSWUNL5XPYR2BTGLYQ7MRG...,None,0.0,0.133302,Tower Bridge,2.948924
4,7LZ6QBXCSKYIUJUSJK2OO3VCHQ5CTWVZVQRGB3C6K6KUR4...,None,0.0,0.120863,Trafalgar Square,2.123317
...,...,...,...,...,...,...
266,WTTKN72SLSR7MMY5TVF6ITSI2PT3WZTYFY6PZPIO7KQ2DL...,None,0.0,0.300487,None,0.617543
267,KQAGOP6B4V4GKGXQNDDLQDRY2PLQ35LGHAHGXGVEEI5OKJ...,None,0.0,0.104548,The British Museum,2.079219
268,AKM4JAMFM7CCHTFK72ACCQMHZ5LF6POZZPB2JANI7DY4Y2...,None,0.0,0.373834,Tower Bridge,5.316881
269,DPCW35BXU2KSMYUIGNDWCMADZZEAQMP67PN7FUCX3EHZAL...,None,0.0,0.22768,Lastminute.com London Eye,10.323751
270,LIPE3D2KSBIVOBBIEQL5HQMM46HIBOUAROPPZ2HKUPUTOG...,None,0.0,0.457073,None,5.548599

In [42]:
merge_ground_truth = pd.merge(df, merged_df, on='image_id', how= 'right')

merge_ground_truth

,image_id,ground_truth,google_vision_sp_detection,google_vision_sp_score,google_vision_sp_response Time,vision_openai_sp_detection,vision_openai_response_time
0,AQ7Q666WK2OXZKIQBQVWPRC5D2M6XFBEHFKQ3MRFV2T2OM...,"[Palace Of Westminster,Big Ben]",None,0.0,0.406496,Big Ben,6.470501
1,TKUAUGKMUUXUYKFE53MLJ64UC2LBDZK22CKY2JXF22ELUS...,[None],None,0.0,0.30369,None,3.266893
2,5FF4Y4LHR5EYDJ7K25U5HUMKWANKYONMVSHQ7ILHOHAX53...,[The Shard],None,0.0,0.341127,The Shard,13.263211
3,OQNB4FXPW3SUEF2CRCJNENGESSWUNL5XPYR2BTGLYQ7MRG...,"[Tower Bridge,The Shard]",None,0.0,0.133302,Tower Bridge,2.948924
4,7LZ6QBXCSKYIUJUSJK2OO3VCHQ5CTWVZVQRGB3C6K6KUR4...,[None],None,0.0,0.120863,Trafalgar Square,2.123317
...,...,...,...,...,...,...,...
266,WTTKN72SLSR7MMY5TVF6ITSI2PT3WZTYFY6PZPIO7KQ2DL...,"[Westminster Bridge,Palace Of Westminster,Big ...",None,0.0,0.300487,None,0.617543
267,KQAGOP6B4V4GKGXQNDDLQDRY2PLQ35LGHAHGXGVEEI5OKJ...,[The British Museum],None,0.0,0.104548,The British Museum,2.079219
268,AKM4JAMFM7CCHTFK72ACCQMHZ5LF6POZZPB2JANI7DY4Y2...,[Tower Bridge],None,0.0,0.373834,Tower Bridge,5.316881
269,DPCW35BXU2KSMYUIGNDWCMADZZEAQMP67PN7FUCX3EHZAL...,[Lastminute.com London Eye],None,0.0,0.22768,Lastminute.com London Eye,10.323751
270,LIPE3D2KSBIVOBBIEQL5HQMM46HIBOUAROPPZ2HKUPUTOG...,[None],None,0.0,0.457073,None,5.548599

,image_id,ground_truth,accommodation_id,longitude,latitude,driving_duration,walking_duration,transit_duration,image,tag_name,probability,accommodation_name,dt,distance_to_bigben,description,score,response_time,response_time_vision,detections_vision_openai
443,SKSGDI523KNGX52RRA6SER3356L72WEHA7PYMZ6SPSQ24N...,"[Westminster Bridge,Palace Of Westminster,Big ...",30440764,-0.12750,51.50722,4,14,10,https://imgcy.trivago.com/partner-images/92/a4...,building,0.9999,Pass The Keys | Cheerful And Cosy Apartment In...,2024-03-07,0.820251,Big Ben,0.486329,0.420697,4.660265,Big Ben
514,SLJLDRFVMHRHWMSJR5FIH5P6QNUWVSKVZ4ZPESU6AOI3SD...,"[Tower Bridge,The Shard]",2498036,-0.08686,51.50411,9,38,23,https://imgcy.trivago.com/partner-images/92/d2...,building,0.9998,"Shangri-La Hotel, At The Shard, London",2024-03-07,2.183695,Tower Bridge,0.841503,0.222265,3.399859,Tower Bridge
572,PC2Q3BIXJXAKS67M47HODAMRKNSGUNTN3GRV4HLA7QGJMX...,"[30 St Mary Axe (The Gherkin),None]",18172382,-0.11265,51.51284,4,7,7,https://imgcy.trivago.com/partner-images/78/b5...,building,0.9999,Eldon Chambers Flat 1,2024-03-07,0.397038,Tower Bridge,0.587840,0.190857,2.660432,Tower Of London
648,GTA6S6SQI2ZLK32TOM2PAQCOEVF7LRFSILP3NUJW4467EI...,[Lastminute.com London Eye],31540182,-0.07798,51.50149,12,48,17,https://imgcy.trivago.com/partner-images/34/c1...,building,0.9999,Tower Bridge Modern 2bed 2bath Apartment By Lo...,2024-03-07,2.860236,Lastminute.com London Eye,0.511336,0.151479,2.856157,Lastminute.com London Eye
742,SCYLZKA62G6RDXV52HJZDHGV263JQID7AUUAXKARY3U2RT...,[Tower Of London],30418188,-0.07358,51.51710,15,48,17,https://imgcy.trivago.com/hotelier-images/90/b...,building,0.9902,Bob W Commercial House,2024-03-07,3.081553,Tower Of London,0.473048,0.100976,1.030194,Tower Of London
898,I5SSLN4TSF5EJOJXEN62PBOVYC6FTVNOTPN22E35JJVGFX...,[30 St Mary Axe (The Gherkin)],18153176,-0.08264,51.51498,10,35,17,https://imgcy.trivago.com/partner-images/47/65...,building,0.9999,"Apartment 4, 48 Bishopsgate",2024-03-07,2.417339,30 St Mary Axe (The Gherkin),0.290306,0.882653,9.223202,30 St Mary Axe (The Gherkin)

In [45]:
merge_ground_truth.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 271 entries, 0 to 270
Data columns (total 7 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   image_id                        271 non-null    object
 1   ground_truth                    270 non-null    object
 2   google_vision_sp_detection      271 non-null    object
 3   google_vision_sp_score          271 non-null    float64
 4   google_vision_sp_response Time  271 non-null    object
 5   vision_openai_sp_detection      271 non-null    object
 6   vision_openai_response_time     271 non-null    float64
dtypes: float64(2), object(5)
memory usage: 16.9+ KB

In [51]:
def extract_first_class(s):
    if not isinstance(s, str):
        # Return a placeholder or handle the error as appropriate
        return None  
    # Check if there's a comma, indicating multiple classes
    if ',' in s:
        # Extract the first class: strip the brackets, split by comma, and take the first element
        first_class = s.strip('[]').split(',')[0].strip()
    else:
        # If there's no comma, it's a single class. Remove brackets and return the class directly.
        first_class = s.strip('[]').strip()
    return first_class

# Apply the function to the 'ground_truth' column
merge_ground_truth['ground_truth_single'] = merge_ground_truth['ground_truth'].apply(extract_first_class)

merge_ground_truth

,image_id,ground_truth,google_vision_sp_detection,google_vision_sp_score,google_vision_sp_response Time,vision_openai_sp_detection,vision_openai_response_time,ground_truth_single
0,AQ7Q666WK2OXZKIQBQVWPRC5D2M6XFBEHFKQ3MRFV2T2OM...,"[Palace Of Westminster,Big Ben]",None,0.0,0.406496,Big Ben,6.470501,Palace Of Westminster
1,TKUAUGKMUUXUYKFE53MLJ64UC2LBDZK22CKY2JXF22ELUS...,[None],None,0.0,0.30369,None,3.266893,None
2,5FF4Y4LHR5EYDJ7K25U5HUMKWANKYONMVSHQ7ILHOHAX53...,[The Shard],None,0.0,0.341127,The Shard,13.263211,The Shard
3,OQNB4FXPW3SUEF2CRCJNENGESSWUNL5XPYR2BTGLYQ7MRG...,"[Tower Bridge,The Shard]",None,0.0,0.133302,Tower Bridge,2.948924,Tower Bridge
4,7LZ6QBXCSKYIUJUSJK2OO3VCHQ5CTWVZVQRGB3C6K6KUR4...,[None],None,0.0,0.120863,Trafalgar Square,2.123317,None
...,...,...,...,...,...,...,...,...
266,WTTKN72SLSR7MMY5TVF6ITSI2PT3WZTYFY6PZPIO7KQ2DL...,"[Westminster Bridge,Palace Of Westminster,Big ...",None,0.0,0.300487,None,0.617543,Westminster Bridge
267,KQAGOP6B4V4GKGXQNDDLQDRY2PLQ35LGHAHGXGVEEI5OKJ...,[The British Museum],None,0.0,0.104548,The British Museum,2.079219,The British Museum
268,AKM4JAMFM7CCHTFK72ACCQMHZ5LF6POZZPB2JANI7DY4Y2...,[Tower Bridge],None,0.0,0.373834,Tower Bridge,5.316881,Tower Bridge
269,DPCW35BXU2KSMYUIGNDWCMADZZEAQMP67PN7FUCX3EHZAL...,[Lastminute.com London Eye],None,0.0,0.22768,Lastminute.com London Eye,10.323751,Lastminute.com London Eye
270,LIPE3D2KSBIVOBBIEQL5HQMM46HIBOUAROPPZ2HKUPUTOG...,[None],None,0.0,0.457073,None,5.548599,None

In [54]:
# Replace brackets at the beginning and end of each string, but keep the content
merge_ground_truth['ground_truth_multiple'] = merge_ground_truth['ground_truth'].str.replace(r'^\[|\]$', '', regex=True)

merge_ground_truth.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 271 entries, 0 to 270
Data columns (total 9 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   image_id                        271 non-null    object
 1   ground_truth                    270 non-null    object
 2   google_vision_sp_detection      271 non-null    object
 3   google_vision_sp_score          271 non-null    float64
 4   google_vision_sp_response Time  271 non-null    object
 5   vision_openai_sp_detection      271 non-null    object
 6   vision_openai_response_time     271 non-null    float64
 7   ground_truth_single             270 non-null    object
 8   ground_truth_multiple           270 non-null    object
dtypes: float64(2), object(7)
memory usage: 21.2+ KB

In [55]:
merge_ground_truth['google_vision_sp_detection'] = merge_ground_truth['google_vision_sp_detection'].astype(str)
merge_ground_truth['vision_openai_sp_detection'] = merge_ground_truth['vision_openai_sp_detection'].astype(str)

In [56]:
merge_ground_truth.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 271 entries, 0 to 270
Data columns (total 9 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   image_id                        271 non-null    object
 1   ground_truth                    270 non-null    object
 2   google_vision_sp_detection      271 non-null    object
 3   google_vision_sp_score          271 non-null    float64
 4   google_vision_sp_response Time  271 non-null    object
 5   vision_openai_sp_detection      271 non-null    object
 6   vision_openai_response_time     271 non-null    float64
 7   ground_truth_single             270 non-null    object
 8   ground_truth_multiple           270 non-null    object
dtypes: float64(2), object(7)
memory usage: 21.2+ KB

In [57]:
merge_ground_truth.to_csv('Google+Openai_SP_Evaluation_Input.csv')